# Generated by Django 4.1.6 on 2023-03-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_taskmodel_deadline_remove_taskmodel_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='priority',
            field=models.CharField(blank=True, choices=[('L', 'L'), ('M', 'M'), ('H', 'H')], default='M', max_length=1),
        ),
    ]
