# Generated by Django 4.1.6 on 2023-03-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_taskmodel_deadline_remove_taskmodel_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='priority',
            field=models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=3, verbose_name='Приоритет'),
        ),
    ]
