# Generated by Django 4.1.6 on 2023-03-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_taskmodel_deadline_remove_taskmodel_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='priority',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Завершено'),
        ),
    ]
