# Generated by Django 4.1.6 on 2023-03-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_taskmodel_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='stuff',
            field=models.CharField(default='Что-то', max_length=250, verbose_name='Что-то'),
            preserve_default=False,
        ),
    ]
