# Generated by Django 4.1.6 on 2023-03-12 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_taskmodel_stuff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='taskmodel',
            name='stuff',
        ),
    ]
