# Generated by Django 4.1.6 on 2023-03-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_taskmodel_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='priority',
            field=models.CharField(default='Средний', max_length=250, verbose_name='Приоритет'),
        ),
    ]
